blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(30)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mailing.urls',namespace='mailing')),
    path('users/',include('users.urls',namespace='users')),
    path('blog/',include('blog.urls',namespace='blog')),
]

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import ClientListView, home, ClientCreateView, ClientUpdateView, MailingListView, MailingCreateView, \
    MailingUpdateView, MailingDetailView, ClientDeleteView, MailingDeleteView

app_name = MailingConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('client/', ClientListView.as_view(), name='client'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('edit_client/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    path('mailing/', MailingListView.as_view(), name='mailing'),
    path('create_mail/', MailingCreateView.as_view(), name='create_mail'),
    path('edit_mail/<int:pk>/', MailingUpdateView.as_view(), name='edit_mail'),
    path('mail_detail/<int:pk>/', MailingDetailView.as_view(), name='mail_detail'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, VerifyEmailView, GenerateAndSendPasswordView, UserUpdateView

app_name=UsersConfig.name

urlpatterns=[
    path('',LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('verify_email/', VerifyEmailView.as_view(), name='verify_email'),
    path('generate_and_send_password/', GenerateAndSendPasswordView.as_view(), name='generate_and_send_password'),

]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    ferst_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, **NULLABLE, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Почта', unique=True)
    coment = models.TextField(**NULLABLE)

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', **NULLABLE)

    def __str__(self):
        return f'{self.ferst_name} {self.email} {self.last_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailing(models.Model):
    PERIOD_DAILY = 'dally'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'ежедневно'),
        (PERIOD_WEEKLY, 'еженедельно'),
        (PERIOD_MONTHLY, 'ежемесечно'),
    )

    STATUS_CREATE = 'create'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'
    STATUS = (
        (STATUS_CREATE, 'создана'),
        (STATUS_STARTED, 'запущена'),
        (STATUS_DONE, 'завершена'),
    )

    time = models.TimeField(verbose_name='Время рассылки',**NULLABLE)
    start_time = models.TimeField(verbose_name='Начало рассылки')
    end_time = models.TimeField(verbose_name='Конец срассылки')
    client = models.ManyToManyField(Client, verbose_name='Клиент')
    period = models.CharField(max_length=50, choices=PERIODS, default=PERIOD_DAILY, verbose_name='Дата рассылки')
    status = models.CharField(max_length=50, choices=STATUS, default=STATUS_CREATE, **NULLABLE,
                              verbose_name='Статус рассылки')

    #message = models.ForeignKey('MessageMailing', on_delete=models.CASCADE, verbose_name='Сообщение', **NULLABLE)

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', **NULLABLE)

    def __str__(self):
        return f'{self.status} {self.client}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MessageMailing(models.Model):
    title = models.CharField(max_length=150, verbose_name='Тема Расслыки')
    body = models.TextField(verbose_name='Текста рассылки')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, **NULLABLE, verbose_name='Рассылка')

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', **NULLABLE)

    def __str__(self):
        return f'{self.title} {self.body}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class LogMailing(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILD = 'faild'
    STATUS_TRY = (
        (STATUS_OK, 'успешно'),
        (STATUS_FAILD, 'ошибка'),
    )
    settings = models.ForeignKey(Mailing, on_delete=models.CASCADE,**NULLABLE, verbose_name='Рассылка')


    last_mailing = models.DateTimeField(auto_now_add=True, verbose_name='Последняя рассылка')
    status_try = models.CharField(max_length=20, choices=STATUS_TRY, verbose_name='Статус попытки')
    answer_mail_server = models.BooleanField(verbose_name='Ответ сервера',**NULLABLE)

    def __str__(self):
        return f'{self.last_mailing} {self.status_try} {self.answer_mail_server}'

    class Meta:
        verbose_name = 'Логи'
        verbose_name_plural = 'Логи'


'''Клиент сервиса:
контактный email,
ФИО,
комментарий.
-Рассылка (настройки):
время рассылки;
периодичность: раз в день, раз в неделю, раз в месяц;
статус рассылки: завершена, создана, запущена.
-Сообщение для рассылки:
тема письма,
тело письма.
-Логи рассылки:
дата и время последней попытки;
статус попытки;
ответ почтового сервера, если он был.
jahontoveu@yandex.ru'''

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing, MessageMailing

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "valid_ver":
                field.widget.attrs['class'] = 'form-control'
class ClientForm(StyleFormMixin,forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('user',)


class MailingForm(StyleFormMixin,forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'
        exclude = ('user','time',)

class MessageForm(StyleFormMixin,forms.ModelForm):
    class Meta:
        model=MessageMailing
        fields = '__all__'
        exclude = ('user',)

mailing/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from blog.models import Blog
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import Client, Mailing, MessageMailing


def home(request):
    blog = Blog.objects.all()
    mailing_is_active = Mailing.objects.filter(status='started')
    client_mailing = Client.objects.all()
    unique_clients = client_mailing.values_list('email', flat=True).distinct()
    random_articles = sample(list(blog), k=min(len(blog), 3))

    context = {
        'random_articles': random_articles,
        'total_mailings': len(client_mailing),
        'active_mailings': len(mailing_is_active),
        'unique_clients': len(unique_clients)
    }

    return render(request, 'mailing/home.html', context)


#####################################################CLIENTS############################################################

class ClientListView(ListView):
    model = Client
    template_name = 'mailing/client.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        if not self.request.user.is_staff:
            queryset = queryset.filter(user=self.request.user)

        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client')


#####################################################Mailing############################################################

class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'mailing/mail_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        if not self.request.user.is_staff:
            queryset = queryset.filter(user=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        for mailing in context['object_list']:
            message_mail = mailing.messagemailing_set.first()
            if message_mail:
                mailing.active_version_title = message_mail.title
                mailing.active_version_body = message_mail.body
            else:
                mailing.active_version_title = 'отсутсвует'
                mailing.active_version_title = None

        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        form.fields['client'].queryset = Client.objects.filter(user=self.request.user)

        return form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        message_formset = inlineformset_factory(Mailing, MessageMailing, form=MessageForm, extra=1)

        if self.request.method == 'POST':
            formset = message_formset(self.request.POST, instance=self.object)
        else:
            formset = message_formset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        form.instance.user = self.request.user
        self.object = form.save()

        if formset.is_valid():
            #form.instance.user = self.request.user
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        message_formset = inlineformset_factory(Mailing, MessageMailing, form=MessageForm, extra=0)

        if self.request.method == 'POST':
            formset = message_formset(self.request.POST, instance=self.object)
        else:
            formset = message_formset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing')

mailing/templates/mailing/base.html
<!doctype html>
<html lang="ru" data-bs-theme="auto">
  <head><script src="/docs/5.3/assets/js/color-modes.js"></script>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="canonical" href="https://bootstrap-4.ru/docs/5.3/examples/product/">

	<!-- Bootstrap core CSS -->
<link href="/static/mailing/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">


    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>


<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
    <circle cx="12" cy="12" r="10"/>
    <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/>
  </symbol>
  <symbol id="cart" viewBox="0 0 16 16">
    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
  <symbol id="chevron-right" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
  </symbol>
</svg>

<nav class="navbar navbar-expand-md bg-dark sticky-top border-bottom" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand d-md-none" href="#">
      <svg class="bi" width="24" height="24"><use xlink:href="#aperture"/></svg>
      Aperture
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" aria-controls="#offcanvas" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="#offcanvas" aria-labelledby="#offcanvasLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="#offcanvasLabel">Aperture</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav flex-grow-1 justify-content-between">
          <li class="nav-item"><a class="nav-link" href="#">
            <svg class="bi" width="24" height="24"><use xlink:href="#aperture"/></svg>
          </a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'mailing:home' %}">Главная</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'mailing:client' %}">База Клиентов</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'mailing:mailing' %}">Рассылки</a></li>
          {% endif %}
          <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog' %}">Наш блог</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Выйти</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'users:profile' %}">Профиль</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Войти</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Регистрация</a></li>
          {% endif %}

          <li class="nav-item"><a class="nav-link" href="#">
            <svg class="bi" width="24" height="24"><use xlink:href="#cart"/></svg>
          </a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-body-secondary">&copy; 2017–2023</small>
    </div>
  </div>
</footer>

<script src="/static/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>


  </body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить клиента "{{ object.ferst_name }} {{ object.last_name }}"?</p>
                        <button type="submit" class="btn btn-outline-primary">Подтвердить</button>
                        <a href="{% url 'mailing:client' %}" class="btn btn-danger">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html'  %}
{% block content %}

<main>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
        <div class="col-md-6 p-lg-5 mx-auto my-5">
            <h1 class="display-3 fw-bold">Вы на странице списка ваших клиентов</h1>
            <h3 class="fw-normal text-muted mb-3">Расширяйте список</h3>

        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>

    <div class="container">
        <div class="row text-center">
            <div class="col-20 mb-5">
                {% if user.is_authenticated %}
                <a class="btn btn-outline-primary" href="{% url 'mailing:create_client' %}">Добавить нового клиента</a>
                {% endif %}
            </div>

            {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{object.ferst_name|title}} {{object.last_name|title}}</h4>
                    </div>
                    <div class="card-body">
                        <h2 class="card-title pricing-card-title">{{object.email}}</h2>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- {{object.coment|slice:100}}</li>
                        </ul>
                        {% if user.is_authenticated %}
                        <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                           href="{% url 'mailing:edit_client' object.pk %}">Изменить</a>
                        {% endif %}
                        <a type="button" class="btn btn-lg btn-block btn-outline-danger" href="{% url 'mailing:client_delete' object.pk %}">Удалить</a>
                    </div>
                    <div class="card-future">
                        {% if user.is_staff %}
                        <spanc class="text-muted">{{ object.user|default:"Автор не указан" }}</spanc>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
</main>
{% endblock %}

mailing/templates/mailing/mail_list.html
{% extends 'mailing/base.html'  %}
{% block content %}
<main>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
        <div class="col-md-6 p-lg-5 mx-auto my-5">
            <h1 class="display-3 fw-bold">Вы на странице рассылок</h1>
            <h3 class="fw-normal text-muted mb-3">Расширяйте список</h3>

        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>

<div class="container">
    <div class="row text-center">
        <div class="col-20 mb-5">
            {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'mailing:create_mail' %}">Добавить новую рассылку</a>
            {% endif %}
        </div>
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.satrt_time|title}}/{{object.end_time|title}}/{{object.period|title}}</h4>
                </div>
                <div class="card-body">
                    {% for client in object.client.all %}
                    <h2 class="card-title pricing-card-title">{{ client.ferst_name }} {{ client.last_name }}</h2>
                    {% endfor %}
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Тема письма: {{object.active_version_title}}</li>

                    </ul>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Сообщение: {{object.active_version_body|slice:100|default:"ТЕКСТ ОТСУТСТВУЕТ"}}</li>

                    </ul>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:mail_detail' object.pk %}">Открыть</a>
                    {% if user.is_authenticated %}
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:edit_mail' object.pk %}">Изменить</a>
                    {% endif %}
                </div>
                <div class="card-future">
                    <a type="button" class="btn btn-lg btn-block btn-outline-danger" href="{% url 'mailing:mailing_delete' object.pk %}">Удалить</a>
                    <spanc class="text-muted">рассылка № {{ object.pk }}</spanc>
                </div>
                <div class="card-future">
                    {% if user.is_staff %}
                    <spanc class="text-muted">{{ object.user|default:"Автор не указан" }}</spanc>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
</main>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html'  %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Рассылка {{ object.id }}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Клиенты рассылки:<br>
                        {% for client in object.client.all %}
                        {{ client.ferst_name }} {{ client.last_name }} / {{ client.email }}<br>
                        {% endfor %}
                    </p>
                    <p>
                        Период рассылки: {{ object.get_period_display }}
                    </p>
                    <p>
                        Статус рассылки: {{ object.get_status_display }}
                    </p>
                    <p>
                        Время начала рассылки: {{ object.start_time }}
                    </p>
                    <p>
                        Время окончания рассылки: {{ object.end_time }}
                    </p>
                    <a type="button" class="btn btn-lg btn-block btn-outline-primary" href="{% url 'mailing:mailing' %}">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}