blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(30)(BlogListView.as_view()), name='blog'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view_blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mailing.urls',namespace='mailing')),
    path('users/',include('users.urls',namespace='users')),
    path('blog/',include('blog.urls',namespace='blog')),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, VerifyEmailView, GenerateAndSendPasswordView, UserUpdateView

app_name=UsersConfig.name

urlpatterns=[
    path('',LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('verify_email/', VerifyEmailView.as_view(), name='verify_email'),
    path('generate_and_send_password/', GenerateAndSendPasswordView.as_view(), name='generate_and_send_password'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE={'blank':True,'null':True}

class User(AbstractUser):
    username=None
    email = models.EmailField(unique=True,verbose_name='почта')

    phone=models.CharField(max_length=150,**NULLABLE,verbose_name='Телефон')
    avatar=models.ImageField(upload_to='users/',**NULLABLE,verbose_name='Аватар')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    verification_token = models.CharField(max_length=15, verbose_name='Код верификации', **NULLABLE)
    is_verified = models.BooleanField(default=False, verbose_name='Статус верификации')

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from mailing.forms import StyleFormMixin
from users.models import User


class UserLoginForm(StyleFormMixin,UserCreationForm):

    class Meta:
        model=User
        fields=('email','password1','password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['password'].widget=forms.HiddenInput()


class PasswordResetForm(StyleFormMixin, forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.views import View
from django.views.generic import CreateView, UpdateView

from users.models import User
from users.forms import PasswordResetForm, UserProfileForm, UserLoginForm
from users.services import send_verification_email, send_password


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserLoginForm
    success_url = reverse_lazy('users:verify_email')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        verification_token = get_random_string(length=15)
        # form.instance.verification_token = verification_token
        send_verification_email(form.instance.email, verification_token)
        #send_mail(
        #    subject='Поздравляем с регестрацией',
        #    message=f'Ваш код подтверждения {verification_token}',
        #    from_email=settings.EMAIL_HOST_USER,
        #    recipient_list=[new_user.email]
        #)
        return super().form_valid(form)

class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserProfileForm

    def get_object(self, queryset=None):
        return self.request.user

class VerifyEmailView(View):
    template_name = 'users/verify_email.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        verification_code = request.POST.get('verification_code')
        User = get_user_model()
        try:
            user = User.objects.get(verification_token=verification_code)
            if not user.is_verified:
                user.is_verified = True
                user.save()
                return redirect('users:confirmation_success')
        except User.DoesNotExist:
            pass
        return redirect('users:login')

class GenerateAndSendPasswordView(View):
    template_name = 'users/generate_and_send_password.html'
    form = PasswordResetForm()

    def get(self, request):
        return render(request, self.template_name, {'form': self.form})

    def post(self, request):
        self.form = PasswordResetForm(request.POST)
        if self.form.is_valid():
            email = self.form.cleaned_data['email']
            if send_password(email):
                return render(request, 'users/password_reset_success.html', {'email': email})
        return render(request, 'users/password_reset_error.html')

users/templates/users/generate_and_send_password.html
{% extends 'mailing/base.html'  %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h2>Password Recovery</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.email.label_tag }}
                {{ form.email }}
                <button type="submit" class="btn btn-outline-success" style="margin-top: 15px;">Send</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html'  %}

{% block content %}
 <div class="row">
     <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                    </form>
                    <div class="card-footer">
                        <a class="btn btn-danger" href="{% url 'users:generate_and_send_password' %}">Забыл пароль</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/password_reset_error.html
{% extends 'mailing/base.html'  %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="alert alert-danger mt-5">
                <h4 class="alert-heading">Password Reset Error!</h4>
                <p>Failed to reset the password for the specified email address <strong>{{ email }}</strong>. Please
                    ensure that the email address is correct and try again.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_success.html
{% extends 'mailing/base.html'  %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="alert alert-success mt-5">
                <h4 class="alert-heading">Password Successfully Reset!</h4>
                <p>A new password has been sent to the address <strong>{{ email }}</strong>. Please check your email and
                    use the new password to log in.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html'  %}

{% block content %}
 <div class="row">
     <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html'  %}

{% block title %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="width: 95%;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">
            {% if request.user.is_staff %}
            Activity status
            {% else %}
            Profile
            {% endif %}
        </h1>
    </div>
    {% endblock %}


    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6 mx-auto text-center">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {% if request.user.is_staff %}
                            Activity of {{ object.email }}
                            {% else %}
                            Profile
                            {% endif %}
                        </h3>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" style="text-align: left;">
                            {% csrf_token %}

                            {% if request.user.is_staff %}
                            <div class="d-flex justify-content-between">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="is_active" name="is_active"
                                           {% if form.is_active.value %}
                                           checked
                                           {% endif %} style="margin-right: 20px; width: 25px; height: 25px;">
                                    <label class="form-check-label" for="is_active"
                                           style="font-size: 20px; font-weight: normal;">
                                        Active
                                    </label>
                                </div>
                                <div class="ml-auto">
                                    <button type="submit" class="btn btn-outline-success">
                                        Save
                                    </button>
                                </div>
                            </div>

                            {% else %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-success">
                                Save
                            </button>
                            {% endif %}

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

users/templates/users/verify_email.html
{% extends 'mailing/base.html'  %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card mt-5">
                <div class="card-body">
                    <h2 class="card-title">Подтверждение почты</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="verification_code">Введите код верификации:</label>
                            <input type="text" class="form-control" id="verification_code" name="verification_code"
                                   required>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}